// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package pbcommon is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	ChatMessage
*/
package pbcommon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatMessage struct {
	Fuid    int64  `protobuf:"varint,1,opt,name=fuid" json:"fuid,omitempty"`
	Funame  string `protobuf:"bytes,2,opt,name=funame" json:"funame,omitempty"`
	Ffigure int32  `protobuf:"varint,3,opt,name=ffigure" json:"ffigure,omitempty"`
	Flevel  int32  `protobuf:"varint,4,opt,name=flevel" json:"flevel,omitempty"`
	Fvip    int32  `protobuf:"varint,5,opt,name=fvip" json:"fvip,omitempty"`
	Tuid    int64  `protobuf:"varint,6,opt,name=tuid" json:"tuid,omitempty"`
	Msg     string `protobuf:"bytes,7,opt,name=msg" json:"msg,omitempty"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetFuid() int64 {
	if m != nil {
		return m.Fuid
	}
	return 0
}

func (m *ChatMessage) GetFuname() string {
	if m != nil {
		return m.Funame
	}
	return ""
}

func (m *ChatMessage) GetFfigure() int32 {
	if m != nil {
		return m.Ffigure
	}
	return 0
}

func (m *ChatMessage) GetFlevel() int32 {
	if m != nil {
		return m.Flevel
	}
	return 0
}

func (m *ChatMessage) GetFvip() int32 {
	if m != nil {
		return m.Fvip
	}
	return 0
}

func (m *ChatMessage) GetTuid() int64 {
	if m != nil {
		return m.Tuid
	}
	return 0
}

func (m *ChatMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "pbcommon.ChatMessage")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x3d, 0x0e, 0xc2, 0x30,
	0x0c, 0x85, 0x15, 0xfa, 0x07, 0x86, 0x01, 0x79, 0x40, 0x1e, 0x2b, 0xa6, 0x4e, 0x2c, 0x1c, 0x81,
	0x99, 0xa5, 0x37, 0x68, 0xc1, 0x29, 0x95, 0x9a, 0xa6, 0x6a, 0x92, 0xde, 0x88, 0x7b, 0xa2, 0xb8,
	0x65, 0xfb, 0xbe, 0x67, 0xd9, 0xcf, 0x70, 0x7a, 0x59, 0x63, 0xec, 0x78, 0x9b, 0x66, 0xeb, 0x2d,
	0xee, 0xa7, 0x76, 0xf5, 0xeb, 0x57, 0xc1, 0xf1, 0xf1, 0x69, 0xfc, 0x93, 0x9d, 0x6b, 0x3a, 0x46,
	0x84, 0x54, 0x87, 0xfe, 0x4d, 0xaa, 0x54, 0x55, 0x52, 0x0b, 0xe3, 0x05, 0x72, 0x1d, 0xc6, 0xc6,
	0x30, 0xed, 0x4a, 0x55, 0x1d, 0xea, 0xcd, 0x90, 0xa0, 0xd0, 0xba, 0xef, 0xc2, 0xcc, 0x94, 0x94,
	0xaa, 0xca, 0xea, 0xbf, 0xca, 0xc6, 0xc0, 0x0b, 0x0f, 0x94, 0xca, 0x60, 0x33, 0xb9, 0xbe, 0xf4,
	0x13, 0x65, 0x92, 0x0a, 0xc7, 0xcc, 0xc7, 0xc6, 0x7c, 0x6d, 0x8c, 0x8c, 0x67, 0x48, 0x8c, 0xeb,
	0xa8, 0x90, 0xba, 0x88, 0x6d, 0x2e, 0x8f, 0xdf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x81, 0xfe,
	0x52, 0x25, 0xc8, 0x00, 0x00, 0x00,
}
