// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package ptuser is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	LoginMsgRequest
	LoginMsgReply
*/
package ptuser

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type LoginMsgRequest struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *LoginMsgRequest) Reset()                    { *m = LoginMsgRequest{} }
func (m *LoginMsgRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginMsgRequest) ProtoMessage()               {}
func (*LoginMsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginMsgRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// The response message containing the greetings
type LoginMsgReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *LoginMsgReply) Reset()                    { *m = LoginMsgReply{} }
func (m *LoginMsgReply) String() string            { return proto.CompactTextString(m) }
func (*LoginMsgReply) ProtoMessage()               {}
func (*LoginMsgReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginMsgReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginMsgRequest)(nil), "ptuser.LoginMsgRequest")
	proto.RegisterType((*LoginMsgReply)(nil), "ptuser.LoginMsgReply")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x28, 0x01, 0xf1, 0x94, 0x94, 0xb9, 0xf8,
	0x7d, 0xf2, 0xd3, 0x33, 0xf3, 0x7c, 0x8b, 0xd3, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0x04, 0xb8, 0x98, 0x4b, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x40, 0x4c, 0x25,
	0x75, 0x2e, 0x5e, 0x84, 0xa2, 0x82, 0x9c, 0x4a, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xd4, 0xe2, 0xd2,
	0x9c, 0x12, 0xb0, 0x2a, 0xd6, 0x20, 0x28, 0x2f, 0x89, 0x0d, 0x6c, 0xb8, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x93, 0x23, 0x98, 0x4e, 0x6a, 0x00, 0x00, 0x00,
}
