// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package ptchat is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	ChatMsgRequest
	ChatMsgReply
*/
package ptchat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type ChatMsgRequest struct {
	Fuid int64  `protobuf:"varint,1,opt,name=fuid" json:"fuid,omitempty"`
	Tuid int64  `protobuf:"varint,2,opt,name=tuid" json:"tuid,omitempty"`
	Msg  string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *ChatMsgRequest) Reset()                    { *m = ChatMsgRequest{} }
func (m *ChatMsgRequest) String() string            { return proto.CompactTextString(m) }
func (*ChatMsgRequest) ProtoMessage()               {}
func (*ChatMsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMsgRequest) GetFuid() int64 {
	if m != nil {
		return m.Fuid
	}
	return 0
}

func (m *ChatMsgRequest) GetTuid() int64 {
	if m != nil {
		return m.Tuid
	}
	return 0
}

func (m *ChatMsgRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// The response message containing the greetings
type ChatMsgReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *ChatMsgReply) Reset()                    { *m = ChatMsgReply{} }
func (m *ChatMsgReply) String() string            { return proto.CompactTextString(m) }
func (*ChatMsgReply) ProtoMessage()               {}
func (*ChatMsgReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatMsgReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*ChatMsgRequest)(nil), "ptchat.ChatMsgRequest")
	proto.RegisterType((*ChatMsgReply)(nil), "ptchat.ChatMsgReply")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x28, 0x01, 0xf1, 0x94, 0xbc, 0xb8, 0xf8,
	0x9c, 0x33, 0x12, 0x4b, 0x7c, 0x8b, 0xd3, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84,
	0xb8, 0x58, 0xd2, 0x4a, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xc0, 0x6c, 0x90,
	0x58, 0x09, 0x48, 0x8c, 0x09, 0x22, 0x06, 0x62, 0x0b, 0x09, 0x70, 0x31, 0xe7, 0x16, 0xa7, 0x4b,
	0x30, 0x2b, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4a, 0x6a, 0x5c, 0x3c, 0x70, 0xb3, 0x0a, 0x72,
	0x2a, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0xc0, 0x66, 0xb1, 0x06, 0x41,
	0x79, 0x49, 0x6c, 0x60, 0x27, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0x47, 0x45, 0x9e,
	0x90, 0x00, 0x00, 0x00,
}
