// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dbrpc.proto

/*
Package dbrpcpt is a generated protocol buffer package.

It is generated from these files:
	dbrpc.proto

It has these top-level messages:
	KeepAliveRequest
	KeepAliveReply
	LoginRequest
	LoginReply
	PushMessageRequest
	PushMessageReply
*/
package dbrpcpt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// KeepAlive
type KeepAliveRequest struct {
	Time int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
}

func (m *KeepAliveRequest) Reset()                    { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string            { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()               {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KeepAliveRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type KeepAliveReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *KeepAliveReply) Reset()                    { *m = KeepAliveReply{} }
func (m *KeepAliveReply) String() string            { return proto.CompactTextString(m) }
func (*KeepAliveReply) ProtoMessage()               {}
func (*KeepAliveReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KeepAliveReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// login
type LoginRequest struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type LoginReply struct {
	Uid        int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Createtime int64  `protobuf:"varint,2,opt,name=createtime" json:"createtime,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Level      int32  `protobuf:"varint,4,opt,name=level" json:"level,omitempty"`
	Exp        int32  `protobuf:"varint,5,opt,name=exp" json:"exp,omitempty"`
	Data       string `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginReply) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginReply) GetCreatetime() int64 {
	if m != nil {
		return m.Createtime
	}
	return 0
}

func (m *LoginReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginReply) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LoginReply) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *LoginReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// push rpc
type PushMessageRequest struct {
	ServerId int32 `protobuf:"varint,1,opt,name=serverId" json:"serverId,omitempty"`
}

func (m *PushMessageRequest) Reset()                    { *m = PushMessageRequest{} }
func (m *PushMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*PushMessageRequest) ProtoMessage()               {}
func (*PushMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PushMessageRequest) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type PushMessageReply struct {
	Type int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
}

func (m *PushMessageReply) Reset()                    { *m = PushMessageReply{} }
func (m *PushMessageReply) String() string            { return proto.CompactTextString(m) }
func (*PushMessageReply) ProtoMessage()               {}
func (*PushMessageReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PushMessageReply) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*KeepAliveRequest)(nil), "dbrpcpt.KeepAliveRequest")
	proto.RegisterType((*KeepAliveReply)(nil), "dbrpcpt.KeepAliveReply")
	proto.RegisterType((*LoginRequest)(nil), "dbrpcpt.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "dbrpcpt.LoginReply")
	proto.RegisterType((*PushMessageRequest)(nil), "dbrpcpt.PushMessageRequest")
	proto.RegisterType((*PushMessageReply)(nil), "dbrpcpt.PushMessageReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DBRPC service

type DBRPCClient interface {
	// KeepAlive rpc
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveReply, error)
	// Login
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
}

type dBRPCClient struct {
	cc *grpc.ClientConn
}

func NewDBRPCClient(cc *grpc.ClientConn) DBRPCClient {
	return &dBRPCClient{cc}
}

func (c *dBRPCClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveReply, error) {
	out := new(KeepAliveReply)
	err := grpc.Invoke(ctx, "/dbrpcpt.DBRPC/KeepAlive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBRPCClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/dbrpcpt.DBRPC/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DBRPC service

type DBRPCServer interface {
	// KeepAlive rpc
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveReply, error)
	// Login
	Login(context.Context, *LoginRequest) (*LoginReply, error)
}

func RegisterDBRPCServer(s *grpc.Server, srv DBRPCServer) {
	s.RegisterService(&_DBRPC_serviceDesc, srv)
}

func _DBRPC_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBRPCServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrpcpt.DBRPC/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBRPCServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBRPC_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBRPCServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrpcpt.DBRPC/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBRPCServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DBRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbrpcpt.DBRPC",
	HandlerType: (*DBRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeepAlive",
			Handler:    _DBRPC_KeepAlive_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _DBRPC_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbrpc.proto",
}

func init() { proto.RegisterFile("dbrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x8d, 0x69, 0xa2, 0x1d, 0x45, 0xca, 0xfa, 0x2f, 0xe6, 0x20, 0x61, 0x0f, 0x92, 0x53,
	0x10, 0xc5, 0x07, 0xa8, 0x7a, 0x11, 0x15, 0x4a, 0xde, 0x20, 0x6d, 0x86, 0x1a, 0xd8, 0x36, 0xeb,
	0xee, 0x26, 0x98, 0xa3, 0x2f, 0xe0, 0x33, 0xcb, 0x4e, 0xd7, 0x10, 0xab, 0xb7, 0x6f, 0x66, 0xbf,
	0xf9, 0x98, 0xf9, 0x2d, 0x1c, 0x94, 0x73, 0x25, 0x17, 0x99, 0x54, 0xb5, 0xa9, 0xd9, 0x1e, 0x15,
	0xd2, 0xf0, 0x2b, 0x98, 0x3c, 0x23, 0xca, 0xa9, 0xa8, 0x5a, 0xcc, 0xf1, 0xbd, 0x41, 0x6d, 0x18,
	0x83, 0x91, 0xa9, 0x56, 0x18, 0x79, 0x89, 0x97, 0xfa, 0x39, 0x69, 0x9e, 0xc2, 0xd1, 0xc0, 0x27,
	0x45, 0xc7, 0xce, 0x20, 0x54, 0xa8, 0x1b, 0x61, 0xc8, 0x17, 0xe4, 0xae, 0xe2, 0x09, 0x1c, 0xbe,
	0xd4, 0xcb, 0x6a, 0xfd, 0x93, 0x36, 0x01, 0xbf, 0xa9, 0x4a, 0x17, 0x66, 0x25, 0xff, 0xf2, 0x00,
	0x9c, 0xc5, 0x06, 0xfd, 0x31, 0xb0, 0x4b, 0x80, 0x85, 0xc2, 0xc2, 0x20, 0xad, 0xb1, 0x4b, 0x0f,
	0x83, 0x8e, 0x5d, 0x70, 0x5d, 0xac, 0x30, 0xf2, 0x13, 0x2f, 0x1d, 0xe7, 0xa4, 0xd9, 0x09, 0x04,
	0x02, 0x5b, 0x14, 0xd1, 0x88, 0xb6, 0xd9, 0x14, 0x36, 0x1b, 0x3f, 0x64, 0x14, 0x50, 0xcf, 0x4a,
	0x3b, 0x5b, 0x16, 0xa6, 0x88, 0xc2, 0xcd, 0xac, 0xd5, 0xfc, 0x1a, 0xd8, 0xac, 0xd1, 0x6f, 0xaf,
	0xa8, 0x75, 0xb1, 0xec, 0x31, 0xc4, 0xb0, 0xaf, 0x51, 0xb5, 0xa8, 0x9e, 0x4a, 0x77, 0x62, 0x5f,
	0x5b, 0x6c, 0xbf, 0x26, 0xec, 0x1d, 0x16, 0x5b, 0x27, 0xd1, 0x79, 0x49, 0xdf, 0x7c, 0x7a, 0x10,
	0x3c, 0xde, 0xe7, 0xb3, 0x07, 0x36, 0x85, 0x71, 0x0f, 0x90, 0x5d, 0x64, 0x8e, 0x7f, 0xb6, 0x0d,
	0x3f, 0x3e, 0xff, 0xef, 0x49, 0x8a, 0x8e, 0xef, 0xb0, 0x3b, 0x08, 0x08, 0x1b, 0x3b, 0xed, 0x3d,
	0x43, 0xd2, 0xf1, 0xf1, 0x76, 0x9b, 0xc6, 0xe6, 0x21, 0x7d, 0xf9, 0xed, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0x7d, 0x75, 0x16, 0x01, 0x02, 0x00, 0x00,
}
