// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mysql.proto

/*
Package pbmysql is a generated protocol buffer package.

It is generated from these files:
	mysql.proto

It has these top-level messages:
	UserField
	OffLineMsgField
*/
package pbmysql

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserField struct {
	Uid            int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Uname          string `protobuf:"bytes,2,opt,name=uname" json:"uname,omitempty"`
	CreateTime     int32  `protobuf:"varint,3,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	LastLoginTime  int32  `protobuf:"varint,4,opt,name=last_login_time,json=lastLoginTime" json:"last_login_time,omitempty"`
	LastLogoutTime int32  `protobuf:"varint,5,opt,name=last_logout_time,json=lastLogoutTime" json:"last_logout_time,omitempty"`
	Vip            int32  `protobuf:"varint,6,opt,name=vip" json:"vip,omitempty"`
	VipLimitTime   int32  `protobuf:"varint,7,opt,name=vip_limit_time,json=vipLimitTime" json:"vip_limit_time,omitempty"`
	Exp            int32  `protobuf:"varint,8,opt,name=exp" json:"exp,omitempty"`
	Level          int32  `protobuf:"varint,9,opt,name=level" json:"level,omitempty"`
	Figure         int32  `protobuf:"varint,10,opt,name=figure" json:"figure,omitempty"`
	EtData         string `protobuf:"bytes,11,opt,name=et_data,json=etData" json:"et_data,omitempty"`
}

func (m *UserField) Reset()                    { *m = UserField{} }
func (m *UserField) String() string            { return proto.CompactTextString(m) }
func (*UserField) ProtoMessage()               {}
func (*UserField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserField) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserField) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *UserField) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *UserField) GetLastLoginTime() int32 {
	if m != nil {
		return m.LastLoginTime
	}
	return 0
}

func (m *UserField) GetLastLogoutTime() int32 {
	if m != nil {
		return m.LastLogoutTime
	}
	return 0
}

func (m *UserField) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *UserField) GetVipLimitTime() int32 {
	if m != nil {
		return m.VipLimitTime
	}
	return 0
}

func (m *UserField) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *UserField) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *UserField) GetFigure() int32 {
	if m != nil {
		return m.Figure
	}
	return 0
}

func (m *UserField) GetEtData() string {
	if m != nil {
		return m.EtData
	}
	return ""
}

type OffLineMsgField struct {
	Uid      int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Id       int64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	SendTime int32  `protobuf:"varint,3,opt,name=send_time,json=sendTime" json:"send_time,omitempty"`
	Fuid     int64  `protobuf:"varint,4,opt,name=fuid" json:"fuid,omitempty"`
	Funame   string `protobuf:"bytes,5,opt,name=funame" json:"funame,omitempty"`
	Ffigure  int32  `protobuf:"varint,6,opt,name=ffigure" json:"ffigure,omitempty"`
	EtData   string `protobuf:"bytes,7,opt,name=et_data,json=etData" json:"et_data,omitempty"`
}

func (m *OffLineMsgField) Reset()                    { *m = OffLineMsgField{} }
func (m *OffLineMsgField) String() string            { return proto.CompactTextString(m) }
func (*OffLineMsgField) ProtoMessage()               {}
func (*OffLineMsgField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OffLineMsgField) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *OffLineMsgField) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OffLineMsgField) GetSendTime() int32 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *OffLineMsgField) GetFuid() int64 {
	if m != nil {
		return m.Fuid
	}
	return 0
}

func (m *OffLineMsgField) GetFuname() string {
	if m != nil {
		return m.Funame
	}
	return ""
}

func (m *OffLineMsgField) GetFfigure() int32 {
	if m != nil {
		return m.Ffigure
	}
	return 0
}

func (m *OffLineMsgField) GetEtData() string {
	if m != nil {
		return m.EtData
	}
	return ""
}

func init() {
	proto.RegisterType((*UserField)(nil), "pbmysql.userField")
	proto.RegisterType((*OffLineMsgField)(nil), "pbmysql.offLineMsgField")
}

func init() { proto.RegisterFile("mysql.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x6b, 0xab, 0x40,
	0x14, 0x85, 0x51, 0xa3, 0xc6, 0x9b, 0xf7, 0x92, 0x30, 0x3c, 0x5e, 0x07, 0xba, 0x68, 0x08, 0xa5,
	0xb8, 0xea, 0xa6, 0x7f, 0xa1, 0x74, 0x95, 0x6e, 0xa4, 0x7b, 0x99, 0xd4, 0x6b, 0xb8, 0x30, 0xea,
	0x54, 0x47, 0x49, 0x7f, 0x55, 0x97, 0xfd, 0x7b, 0x65, 0xee, 0x18, 0xc8, 0xa6, 0xbb, 0x7b, 0xce,
	0x7c, 0x17, 0x8f, 0xe7, 0xc2, 0xaa, 0xf9, 0x1c, 0x3e, 0xf4, 0xa3, 0xe9, 0x3b, 0xdb, 0x89, 0xd4,
	0x1c, 0x59, 0xee, 0xbf, 0x43, 0xc8, 0xc6, 0x01, 0xfb, 0x17, 0x42, 0x5d, 0x89, 0x2d, 0x44, 0x23,
	0x55, 0x32, 0xd8, 0x05, 0x79, 0x54, 0xb8, 0x51, 0xfc, 0x83, 0x78, 0x6c, 0x55, 0x83, 0x32, 0xdc,
	0x05, 0x79, 0x56, 0x78, 0x21, 0xee, 0x60, 0xf5, 0xde, 0xa3, 0xb2, 0x58, 0x5a, 0x6a, 0x50, 0x46,
	0xbb, 0x20, 0x8f, 0x0b, 0xf0, 0xd6, 0x1b, 0x35, 0x28, 0x1e, 0x60, 0xa3, 0xd5, 0x60, 0x4b, 0xdd,
	0x9d, 0xa8, 0xf5, 0xd0, 0x82, 0xa1, 0xbf, 0xce, 0x3e, 0x38, 0x97, 0xb9, 0x1c, 0xb6, 0x17, 0xae,
	0x1b, 0xad, 0x07, 0x63, 0x06, 0xd7, 0x33, 0xd8, 0x8d, 0x96, 0xc9, 0x2d, 0x44, 0x13, 0x19, 0x99,
	0xf0, 0xa3, 0x1b, 0xc5, 0x3d, 0xac, 0x27, 0x32, 0xa5, 0xa6, 0x86, 0xe6, 0xcd, 0x94, 0x1f, 0xff,
	0x4c, 0x64, 0x0e, 0xce, 0xbc, 0xec, 0xe1, 0xd9, 0xc8, 0xa5, 0xdf, 0xc3, 0xb3, 0x71, 0xbf, 0xa4,
	0x71, 0x42, 0x2d, 0x33, 0xf6, 0xbc, 0x10, 0xff, 0x21, 0xa9, 0xe9, 0x34, 0xf6, 0x28, 0x81, 0xed,
	0x59, 0x89, 0x1b, 0x48, 0xd1, 0x96, 0x95, 0xb2, 0x4a, 0xae, 0xb8, 0x82, 0x04, 0xed, 0xb3, 0xb2,
	0x6a, 0xff, 0x15, 0xc0, 0xa6, 0xab, 0xeb, 0x03, 0xb5, 0xf8, 0x3a, 0x9c, 0x7e, 0xeb, 0x6f, 0x0d,
	0x21, 0x55, 0x5c, 0x5e, 0x54, 0x84, 0x54, 0x89, 0x5b, 0xc8, 0x06, 0x6c, 0xab, 0xeb, 0xde, 0x96,
	0xce, 0xe0, 0xac, 0x02, 0x16, 0xb5, 0xdb, 0x5f, 0x30, 0xce, 0x33, 0xe7, 0xf2, 0x17, 0x88, 0xfd,
	0xe7, 0xbd, 0x12, 0x12, 0xd2, 0x7a, 0x0e, 0xec, 0x3b, 0xb9, 0xc8, 0xeb, 0xc4, 0xe9, 0x75, 0xe2,
	0x63, 0xc2, 0xb7, 0x7f, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x0f, 0x8b, 0x9b, 0x0a, 0x02,
	0x00, 0x00,
}
