// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ctrpc.proto

/*
Package ctrpcpt is a generated protocol buffer package.

It is generated from these files:
	ctrpc.proto

It has these top-level messages:
	KeepAliveRequest
	KeepAliveReply
	LoginRequest
	LoginReply
	PushMessageRequest
	PushMessageReply
*/
package ctrpcpt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// KeepAlive
type KeepAliveRequest struct {
	Time int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
}

func (m *KeepAliveRequest) Reset()                    { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string            { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()               {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KeepAliveRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type KeepAliveReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *KeepAliveReply) Reset()                    { *m = KeepAliveReply{} }
func (m *KeepAliveReply) String() string            { return proto.CompactTextString(m) }
func (*KeepAliveReply) ProtoMessage()               {}
func (*KeepAliveReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KeepAliveReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// login
type LoginRequest struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type LoginReply struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// push rpc
type PushMessageRequest struct {
	ServerId int32 `protobuf:"varint,1,opt,name=serverId" json:"serverId,omitempty"`
}

func (m *PushMessageRequest) Reset()                    { *m = PushMessageRequest{} }
func (m *PushMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*PushMessageRequest) ProtoMessage()               {}
func (*PushMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PushMessageRequest) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type PushMessageReply struct {
	Type int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
}

func (m *PushMessageReply) Reset()                    { *m = PushMessageReply{} }
func (m *PushMessageReply) String() string            { return proto.CompactTextString(m) }
func (*PushMessageReply) ProtoMessage()               {}
func (*PushMessageReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PushMessageReply) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*KeepAliveRequest)(nil), "ctrpcpt.KeepAliveRequest")
	proto.RegisterType((*KeepAliveReply)(nil), "ctrpcpt.KeepAliveReply")
	proto.RegisterType((*LoginRequest)(nil), "ctrpcpt.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "ctrpcpt.LoginReply")
	proto.RegisterType((*PushMessageRequest)(nil), "ctrpcpt.PushMessageRequest")
	proto.RegisterType((*PushMessageReply)(nil), "ctrpcpt.PushMessageReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CTRPC service

type CTRPCClient interface {
	// KeepAlive rpc
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveReply, error)
	// Login
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	PushStream(ctx context.Context, in *PushMessageRequest, opts ...grpc.CallOption) (CTRPC_PushStreamClient, error)
}

type cTRPCClient struct {
	cc *grpc.ClientConn
}

func NewCTRPCClient(cc *grpc.ClientConn) CTRPCClient {
	return &cTRPCClient{cc}
}

func (c *cTRPCClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveReply, error) {
	out := new(KeepAliveReply)
	err := grpc.Invoke(ctx, "/ctrpcpt.CTRPC/KeepAlive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cTRPCClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/ctrpcpt.CTRPC/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cTRPCClient) PushStream(ctx context.Context, in *PushMessageRequest, opts ...grpc.CallOption) (CTRPC_PushStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CTRPC_serviceDesc.Streams[0], c.cc, "/ctrpcpt.CTRPC/PushStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &cTRPCPushStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CTRPC_PushStreamClient interface {
	Recv() (*PushMessageReply, error)
	grpc.ClientStream
}

type cTRPCPushStreamClient struct {
	grpc.ClientStream
}

func (x *cTRPCPushStreamClient) Recv() (*PushMessageReply, error) {
	m := new(PushMessageReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CTRPC service

type CTRPCServer interface {
	// KeepAlive rpc
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveReply, error)
	// Login
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	PushStream(*PushMessageRequest, CTRPC_PushStreamServer) error
}

func RegisterCTRPCServer(s *grpc.Server, srv CTRPCServer) {
	s.RegisterService(&_CTRPC_serviceDesc, srv)
}

func _CTRPC_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CTRPCServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ctrpcpt.CTRPC/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CTRPCServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CTRPC_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CTRPCServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ctrpcpt.CTRPC/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CTRPCServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CTRPC_PushStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PushMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CTRPCServer).PushStream(m, &cTRPCPushStreamServer{stream})
}

type CTRPC_PushStreamServer interface {
	Send(*PushMessageReply) error
	grpc.ServerStream
}

type cTRPCPushStreamServer struct {
	grpc.ServerStream
}

func (x *cTRPCPushStreamServer) Send(m *PushMessageReply) error {
	return x.ServerStream.SendMsg(m)
}

var _CTRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ctrpcpt.CTRPC",
	HandlerType: (*CTRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeepAlive",
			Handler:    _CTRPC_KeepAlive_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _CTRPC_Login_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushStream",
			Handler:       _CTRPC_PushStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ctrpc.proto",
}

func init() { proto.RegisterFile("ctrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdd, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0x0d, 0x35, 0xd5, 0x1e, 0x45, 0xca, 0x88, 0x3f, 0x8d, 0x37, 0x65, 0x11, 0xe9, 0x55,
	0x28, 0x8a, 0x0f, 0x50, 0x7a, 0xa3, 0xa8, 0x50, 0xa2, 0x2f, 0x50, 0xdb, 0xa1, 0x06, 0x52, 0xb3,
	0xee, 0x4f, 0x21, 0xcf, 0xe8, 0x4b, 0xc9, 0xae, 0xeb, 0x52, 0xdb, 0xde, 0xcd, 0xc9, 0x9c, 0x39,
	0x99, 0x6f, 0x16, 0x47, 0x33, 0xa3, 0xe4, 0x2c, 0x97, 0xaa, 0x36, 0x35, 0x1d, 0x78, 0x21, 0x8d,
	0xb8, 0x41, 0xf7, 0x89, 0x59, 0x8e, 0xaa, 0x72, 0xc5, 0x05, 0x7f, 0x59, 0xd6, 0x86, 0x08, 0xfb,
	0xa6, 0x5c, 0xf2, 0x65, 0xd2, 0x4f, 0x06, 0xad, 0xc2, 0xd7, 0x62, 0x80, 0x93, 0x35, 0x9f, 0xac,
	0x1a, 0x3a, 0x47, 0x5b, 0xb1, 0xb6, 0x95, 0xf1, 0xbe, 0xb4, 0x08, 0x4a, 0xf4, 0x71, 0xfc, 0x5c,
	0x2f, 0xca, 0xcf, 0xbf, 0xb4, 0x2e, 0x5a, 0xb6, 0x9c, 0x87, 0x30, 0x57, 0x8a, 0x6b, 0x20, 0x38,
	0xb6, 0x73, 0x3a, 0x31, 0x67, 0x08, 0x9a, 0x58, 0xfd, 0xf1, 0xc2, 0x5a, 0x4f, 0x17, 0x71, 0xb7,
	0x0c, 0x87, 0x9a, 0xd5, 0x8a, 0xd5, 0xe3, 0x3c, 0xfc, 0x37, 0x6a, 0xc7, 0xf2, 0x6f, 0xc2, 0xa5,
	0x3b, 0x96, 0x46, 0x72, 0xf0, 0xfa, 0xfa, 0xf6, 0x3b, 0x41, 0x3a, 0x7e, 0x2b, 0x26, 0x63, 0x1a,
	0xa1, 0x13, 0xa9, 0xa8, 0x97, 0x87, 0xa3, 0xe4, 0x9b, 0x17, 0xc9, 0x2e, 0x76, 0xb5, 0x64, 0xd5,
	0x88, 0x3d, 0xba, 0x47, 0xea, 0x61, 0xe8, 0x2c, 0x7a, 0xd6, 0xf1, 0xb3, 0xd3, 0xcd, 0xcf, 0xbf,
	0x63, 0x0f, 0x80, 0xdb, 0xf5, 0xd5, 0x28, 0x9e, 0x2e, 0xe9, 0x2a, 0x9a, 0xb6, 0x91, 0xb3, 0xde,
	0xee, 0xa6, 0xcf, 0x19, 0x26, 0xef, 0x6d, 0xff, 0xa2, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xe1, 0x38, 0x2a, 0x28, 0xe0, 0x01, 0x00, 0x00,
}
