// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	chat.proto
	message.proto
	user.proto

It has these top-level messages:
	ChatMsgRequest
	ChatMsgReply
	Message
	LoginMsgRequest
	LoginMsgReply
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type ChatMsgRequest struct {
	Fuid int64  `protobuf:"varint,1,opt,name=fuid" json:"fuid,omitempty"`
	Tuid int64  `protobuf:"varint,2,opt,name=tuid" json:"tuid,omitempty"`
	Msg  string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *ChatMsgRequest) Reset()                    { *m = ChatMsgRequest{} }
func (m *ChatMsgRequest) String() string            { return proto.CompactTextString(m) }
func (*ChatMsgRequest) ProtoMessage()               {}
func (*ChatMsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMsgRequest) GetFuid() int64 {
	if m != nil {
		return m.Fuid
	}
	return 0
}

func (m *ChatMsgRequest) GetTuid() int64 {
	if m != nil {
		return m.Tuid
	}
	return 0
}

func (m *ChatMsgRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// The response message containing the greetings
type ChatMsgReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *ChatMsgReply) Reset()                    { *m = ChatMsgReply{} }
func (m *ChatMsgReply) String() string            { return proto.CompactTextString(m) }
func (*ChatMsgReply) ProtoMessage()               {}
func (*ChatMsgReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatMsgReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*ChatMsgRequest)(nil), "message.ChatMsgRequest")
	proto.RegisterType((*ChatMsgReply)(nil), "message.ChatMsgReply")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55,
	0xf2, 0xe2, 0xe2, 0x73, 0xce, 0x48, 0x2c, 0xf1, 0x2d, 0x4e, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x2b, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e,
	0x02, 0xb3, 0x41, 0x62, 0x25, 0x20, 0x31, 0x26, 0x88, 0x18, 0x88, 0x2d, 0x24, 0xc0, 0xc5, 0x9c,
	0x5b, 0x9c, 0x2e, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x2a, 0xa9, 0x71, 0xf1, 0xc0,
	0xcd, 0x2a, 0xc8, 0xa9, 0x14, 0x12, 0xe3, 0x62, 0x2b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x01, 0x9b,
	0xc5, 0x1a, 0x04, 0xe5, 0x25, 0xb1, 0x81, 0xdd, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0e,
	0xbd, 0xf0, 0xac, 0x91, 0x00, 0x00, 0x00,
}
