// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	chat.proto
	message.proto
	user.proto

It has these top-level messages:
	ChatMessage
	ChatMsgRequest
	ChatMsgReply
	ChatMsgPush
	Message
	LoginMsgRequest
	LoginMsgReply
	LogOutMsgRequest
	LogOutMsgReply
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatMessage struct {
	Fuid    int64  `protobuf:"varint,1,opt,name=fuid" json:"fuid,omitempty"`
	Funame  string `protobuf:"bytes,2,opt,name=funame" json:"funame,omitempty"`
	Ffigure int32  `protobuf:"varint,3,opt,name=ffigure" json:"ffigure,omitempty"`
	Flevel  int32  `protobuf:"varint,4,opt,name=flevel" json:"flevel,omitempty"`
	Fvip    int32  `protobuf:"varint,5,opt,name=fvip" json:"fvip,omitempty"`
	Tuid    int64  `protobuf:"varint,6,opt,name=tuid" json:"tuid,omitempty"`
	Msg     string `protobuf:"bytes,7,opt,name=msg" json:"msg,omitempty"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetFuid() int64 {
	if m != nil {
		return m.Fuid
	}
	return 0
}

func (m *ChatMessage) GetFuname() string {
	if m != nil {
		return m.Funame
	}
	return ""
}

func (m *ChatMessage) GetFfigure() int32 {
	if m != nil {
		return m.Ffigure
	}
	return 0
}

func (m *ChatMessage) GetFlevel() int32 {
	if m != nil {
		return m.Flevel
	}
	return 0
}

func (m *ChatMessage) GetFvip() int32 {
	if m != nil {
		return m.Fvip
	}
	return 0
}

func (m *ChatMessage) GetTuid() int64 {
	if m != nil {
		return m.Tuid
	}
	return 0
}

func (m *ChatMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ChatMsgRequest struct {
	Msg *ChatMessage `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *ChatMsgRequest) Reset()                    { *m = ChatMsgRequest{} }
func (m *ChatMsgRequest) String() string            { return proto.CompactTextString(m) }
func (*ChatMsgRequest) ProtoMessage()               {}
func (*ChatMsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatMsgRequest) GetMsg() *ChatMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

// The response message containing the greetings
type ChatMsgReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *ChatMsgReply) Reset()                    { *m = ChatMsgReply{} }
func (m *ChatMsgReply) String() string            { return proto.CompactTextString(m) }
func (*ChatMsgReply) ProtoMessage()               {}
func (*ChatMsgReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChatMsgReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ChatMsgPush struct {
	Msg *ChatMessage `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *ChatMsgPush) Reset()                    { *m = ChatMsgPush{} }
func (m *ChatMsgPush) String() string            { return proto.CompactTextString(m) }
func (*ChatMsgPush) ProtoMessage()               {}
func (*ChatMsgPush) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ChatMsgPush) GetMsg() *ChatMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "message.ChatMessage")
	proto.RegisterType((*ChatMsgRequest)(nil), "message.ChatMsgRequest")
	proto.RegisterType((*ChatMsgReply)(nil), "message.ChatMsgReply")
	proto.RegisterType((*ChatMsgPush)(nil), "message.ChatMsgPush")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0xdd, 0xb6, 0x38, 0x2b, 0x22, 0x41, 0x24, 0xc7, 0xd2, 0xc3, 0xd2, 0x53, 0x0f,
	0x8a, 0xe0, 0xdd, 0xb3, 0x20, 0x79, 0x83, 0xa8, 0x93, 0xb4, 0x90, 0xba, 0xb5, 0x93, 0x2c, 0xf8,
	0x40, 0xbe, 0xa7, 0x64, 0x12, 0xc5, 0xa3, 0xb7, 0xff, 0x9b, 0xe4, 0x9f, 0xf9, 0x67, 0x00, 0x5e,
	0x27, 0x13, 0xc6, 0x75, 0x3b, 0x86, 0xa3, 0x6c, 0x17, 0x24, 0x32, 0x0e, 0xfb, 0x2f, 0x01, 0xfb,
	0xc7, 0xc9, 0x84, 0xa7, 0xcc, 0x52, 0xc2, 0xce, 0xc6, 0xf9, 0x4d, 0x89, 0x4e, 0x0c, 0x95, 0x66,
	0x2d, 0x6f, 0xa0, 0xb1, 0xf1, 0xdd, 0x2c, 0xa8, 0xce, 0x3a, 0x31, 0x9c, 0xeb, 0x42, 0x52, 0x41,
	0x6b, 0xed, 0xec, 0xe2, 0x86, 0xaa, 0xea, 0xc4, 0x50, 0xeb, 0x1f, 0x64, 0x87, 0xc7, 0x13, 0x7a,
	0xb5, 0xe3, 0x87, 0x42, 0xdc, 0xfd, 0x34, 0xaf, 0xaa, 0xe6, 0x2a, 0xeb, 0x54, 0x0b, 0x69, 0x62,
	0x93, 0x27, 0x26, 0x2d, 0xaf, 0xa0, 0x5a, 0xc8, 0xa9, 0x96, 0xc7, 0x25, 0xd9, 0x3f, 0xc0, 0x25,
	0xc7, 0x24, 0xa7, 0xf1, 0x23, 0x22, 0x05, 0x79, 0xc8, 0x7f, 0x52, 0xd0, 0xfd, 0xed, 0xf5, 0x58,
	0x16, 0x1a, 0xff, 0x2c, 0x93, 0x9d, 0x07, 0xb8, 0xf8, 0x75, 0xae, 0xfe, 0x33, 0x65, 0xdb, 0x90,
	0xa2, 0x0f, 0x6c, 0xad, 0x75, 0xa1, 0xfe, 0xbe, 0x1c, 0x82, 0xdc, 0x73, 0xa4, 0xe9, 0xbf, 0xed,
	0x5f, 0x1a, 0x3e, 0xe8, 0xdd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0x0e, 0xb2, 0x74, 0x5e,
	0x01, 0x00, 0x00,
}
