// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// login request
type LoginRequest struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *LoginRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// login reply
type LoginReply struct {
	Result    int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *LoginReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *LoginReply) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// logout request
type LogOutRequest struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *LogOutRequest) Reset()                    { *m = LogOutRequest{} }
func (m *LogOutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogOutRequest) ProtoMessage()               {}
func (*LogOutRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *LogOutRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// logout reply
type LogOutReply struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *LogOutReply) Reset()                    { *m = LogOutReply{} }
func (m *LogOutReply) String() string            { return proto.CompactTextString(m) }
func (*LogOutReply) ProtoMessage()               {}
func (*LogOutReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *LogOutReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// register request
type RegisterRequest struct {
	Uname    string `protobuf:"bytes,1,opt,name=uname" json:"uname,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Gender   int32  `protobuf:"varint,4,opt,name=gender" json:"gender,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *RegisterRequest) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

// register reply
type RegisterReply struct {
	Uname string `protobuf:"bytes,1,opt,name=uname" json:"uname,omitempty"`
	Ret   int32  `protobuf:"varint,2,opt,name=ret" json:"ret,omitempty"`
}

func (m *RegisterReply) Reset()                    { *m = RegisterReply{} }
func (m *RegisterReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()               {}
func (*RegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *RegisterReply) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *RegisterReply) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

// keepAlive request
type KeepAliveRequest struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *KeepAliveRequest) Reset()                    { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string            { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()               {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *KeepAliveRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// register reply
type KeepAliveReply struct {
}

func (m *KeepAliveReply) Reset()                    { *m = KeepAliveReply{} }
func (m *KeepAliveReply) String() string            { return proto.CompactTextString(m) }
func (*KeepAliveReply) ProtoMessage()               {}
func (*KeepAliveReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func init() {
	proto.RegisterType((*LoginRequest)(nil), "message.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "message.LoginReply")
	proto.RegisterType((*LogOutRequest)(nil), "message.LogOutRequest")
	proto.RegisterType((*LogOutReply)(nil), "message.LogOutReply")
	proto.RegisterType((*RegisterRequest)(nil), "message.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "message.RegisterReply")
	proto.RegisterType((*KeepAliveRequest)(nil), "message.KeepAliveRequest")
	proto.RegisterType((*KeepAliveReply)(nil), "message.KeepAliveReply")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xfc, 0x30,
	0x10, 0xc5, 0xd9, 0x7f, 0xff, 0x5d, 0xed, 0xe8, 0x6a, 0x09, 0x22, 0x45, 0x3c, 0xac, 0x41, 0xc1,
	0x93, 0x17, 0x0f, 0x9e, 0xf5, 0xea, 0x82, 0x90, 0x6f, 0x10, 0xe9, 0x10, 0x02, 0x49, 0x93, 0xcd,
	0x24, 0xca, 0x7e, 0x7b, 0x49, 0xda, 0xba, 0x0b, 0xea, 0xed, 0xbd, 0xc9, 0x9b, 0xfc, 0x66, 0x18,
	0x80, 0x44, 0x18, 0x1e, 0x7c, 0x70, 0xd1, 0xb1, 0x23, 0x8b, 0x44, 0x52, 0x21, 0x5f, 0xc3, 0xe9,
	0xc6, 0x29, 0x3d, 0x08, 0xdc, 0x26, 0xa4, 0xc8, 0x5a, 0xa8, 0x92, 0xee, 0xbb, 0xc5, 0x7a, 0x71,
	0x5f, 0x89, 0x2c, 0xf9, 0x0b, 0xc0, 0x94, 0xf0, 0x66, 0xc7, 0x2e, 0x61, 0x19, 0x90, 0x92, 0x89,
	0x25, 0x52, 0x8b, 0xc9, 0xb1, 0x6b, 0x68, 0xa2, 0xb6, 0x48, 0x51, 0x5a, 0xdf, 0xfd, 0x2b, 0xdd,
	0xfb, 0x02, 0xbf, 0x81, 0xd5, 0xc6, 0xa9, 0xb7, 0x14, 0xff, 0xc6, 0xdc, 0xc1, 0xc9, 0x1c, 0xf9,
	0xc9, 0x69, 0x66, 0x0e, 0xdf, 0xc2, 0xb9, 0x40, 0xa5, 0x29, 0x62, 0x98, 0xff, 0xba, 0x80, 0x3a,
	0x0d, 0xd2, 0xe2, 0x94, 0x1c, 0x4d, 0xae, 0xa2, 0x95, 0xda, 0x94, 0x61, 0x1a, 0x31, 0x1a, 0x76,
	0x05, 0xc7, 0x5e, 0x12, 0x7d, 0xba, 0xd0, 0x77, 0x55, 0x79, 0xf8, 0xf6, 0x19, 0xa9, 0x70, 0xe8,
	0x31, 0x74, 0xff, 0xc7, 0xd5, 0x46, 0xc7, 0x9f, 0x60, 0xb5, 0x47, 0xe6, 0xd9, 0x7e, 0x07, 0xb6,
	0x50, 0x05, 0x8c, 0x05, 0x57, 0x8b, 0x2c, 0xf9, 0x2d, 0xb4, 0xaf, 0x88, 0xfe, 0xd9, 0xe8, 0x0f,
	0x3c, 0x58, 0xdc, 0x92, 0x9a, 0x3a, 0xb3, 0xe4, 0x2d, 0x9c, 0x1d, 0xa4, 0xbc, 0xd9, 0xbd, 0x2f,
	0xcb, 0x8d, 0x1e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x48, 0x63, 0xb8, 0x75, 0xb1, 0x01, 0x00,
	0x00,
}
