// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// login request
type LoginMsgRequest struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *LoginMsgRequest) Reset()                    { *m = LoginMsgRequest{} }
func (m *LoginMsgRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginMsgRequest) ProtoMessage()               {}
func (*LoginMsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *LoginMsgRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// login reply
type LoginMsgReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *LoginMsgReply) Reset()                    { *m = LoginMsgReply{} }
func (m *LoginMsgReply) String() string            { return proto.CompactTextString(m) }
func (*LoginMsgReply) ProtoMessage()               {}
func (*LoginMsgReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *LoginMsgReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// logout request
type LogOutMsgRequest struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *LogOutMsgRequest) Reset()                    { *m = LogOutMsgRequest{} }
func (m *LogOutMsgRequest) String() string            { return proto.CompactTextString(m) }
func (*LogOutMsgRequest) ProtoMessage()               {}
func (*LogOutMsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *LogOutMsgRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// logout reply
type LogOutMsgReply struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *LogOutMsgReply) Reset()                    { *m = LogOutMsgReply{} }
func (m *LogOutMsgReply) String() string            { return proto.CompactTextString(m) }
func (*LogOutMsgReply) ProtoMessage()               {}
func (*LogOutMsgReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *LogOutMsgReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginMsgRequest)(nil), "message.LoginMsgRequest")
	proto.RegisterType((*LoginMsgReply)(nil), "message.LoginMsgReply")
	proto.RegisterType((*LogOutMsgRequest)(nil), "message.LogOutMsgRequest")
	proto.RegisterType((*LogOutMsgReply)(nil), "message.LogOutMsgReply")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55,
	0x52, 0xe6, 0xe2, 0xf7, 0xc9, 0x4f, 0xcf, 0xcc, 0xf3, 0x2d, 0x4e, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e,
	0x02, 0x31, 0x95, 0xd4, 0xb9, 0x78, 0x11, 0x8a, 0x0a, 0x72, 0x2a, 0x85, 0xc4, 0xb8, 0xd8, 0x8a,
	0x52, 0x8b, 0x4b, 0x73, 0x4a, 0xc0, 0xaa, 0x58, 0x83, 0xa0, 0x3c, 0x25, 0x15, 0x2e, 0x01, 0x9f,
	0xfc, 0x74, 0xff, 0xd2, 0x12, 0xbc, 0xc6, 0x69, 0x70, 0xf1, 0x21, 0xa9, 0xc2, 0x34, 0x8f, 0x13,
	0x66, 0x5e, 0x12, 0x1b, 0xd8, 0xb5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xce, 0xa3, 0x8d,
	0x31, 0xbb, 0x00, 0x00, 0x00,
}
